name: shift_jis
description: Flutter plugin for Shift_JIS encoding and decoding, using platform channels.
version: 0.3.1
homepage: https://github.com/imamurh/shift_jis

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.imamurh.shift_jis
        pluginClass: ShiftJisPlugin
      ios:
        pluginClass: ShiftJisPlugin
